//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.VisualStudio.ServiceReference.Platforms, version 15.0.26323.1
// 
namespace QuickyApp.TranslateApp.UI.TranslateService {
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DriverTypes", Namespace="http://schemas.datacontract.org/2004/07/QuickyApp.TranslateApp.Engine.Enums")]
    public enum DriverTypes : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ChromeDriver = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PhantomJSDriver = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FirefoxDriver = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ExplorerDriver = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TranslateWord", Namespace="http://schemas.datacontract.org/2004/07/QuickyApp.TranslateApp.Engine.Wcf")]
    public partial class TranslateWord : object, System.ComponentModel.INotifyPropertyChanged {
        
        private QuickyApp.TranslateApp.UI.TranslateService.TranslateLanguages LanguageField;
        
        private string WordField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public QuickyApp.TranslateApp.UI.TranslateService.TranslateLanguages Language {
            get {
                return this.LanguageField;
            }
            set {
                if ((this.LanguageField.Equals(value) != true)) {
                    this.LanguageField = value;
                    this.RaisePropertyChanged("Language");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Word {
            get {
                return this.WordField;
            }
            set {
                if ((object.ReferenceEquals(this.WordField, value) != true)) {
                    this.WordField = value;
                    this.RaisePropertyChanged("Word");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TranslateLanguages", Namespace="http://schemas.datacontract.org/2004/07/QuickyApp.TranslateApp.Engine.Enums")]
    public enum TranslateLanguages : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Afrikaans = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Albanian = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Amharic = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Arabic = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Armenian = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Azerbaijani = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Basque = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Belarusian = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Bengali = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Bosnian = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Bulgarian = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Catalan = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Cebuano = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Chichewa = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ChineseSimplified = 14,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ChineseTraditional = 15,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Corsican = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Croatian = 17,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Czech = 18,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Danish = 19,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Dutch = 20,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        English = 21,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Esperato = 22,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Estonan = 23,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Filipino = 24,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Finnish = 25,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        French = 26,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Frisian = 27,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Galician = 28,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Georgian = 29,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        German = 30,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Greek = 31,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Gujarati = 32,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HaitianCreole = 33,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Hausa = 34,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Hawaiian = 35,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Hebrew = 36,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Hindi = 37,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Hmong = 38,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Hungarian = 39,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Icelandic = 40,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Igbo = 41,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Indonesian = 42,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Irish = 43,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Italian = 44,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Japanese = 45,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Javanese = 46,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Kannada = 47,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Kazakh = 48,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Khmer = 49,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Korean = 50,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        KurdishKurmanji = 51,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Kyrgyz = 52,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Lao = 53,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Latin = 54,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Latvian = 55,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Lithuanian = 56,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Luxembourgish = 57,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Macedonian = 58,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Malagasy = 59,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Malay = 60,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Malayalam = 61,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Maltese = 62,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Maori = 63,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Marathi = 64,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Mongolian = 65,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MynamarBurmese = 66,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Nepali = 67,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Norwegian = 68,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Pashto = 69,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Persian = 70,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Polish = 71,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Portuguese = 72,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Punjabi = 73,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Romanian = 74,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Russian = 75,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Samoan = 76,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ScotsGaelic = 77,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Serbian = 78,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Sesotho = 79,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Shona = 80,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Sindhi = 81,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Sinhala = 82,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Slovak = 83,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Slovenian = 84,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Somali = 85,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Spanish = 86,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Sundanese = 87,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Swahili = 88,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Swedish = 89,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Tajik = 90,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Tamil = 91,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Telugu = 92,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Thai = 93,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Turkish = 94,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Ukrainian = 95,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Urdu = 96,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Uzbek = 97,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Vietnamese = 98,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Welsh = 99,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Xhosa = 100,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Yiddish = 101,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Yoruba = 102,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Zulu = 103,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TranslateService.ITranslateService")]
    public interface ITranslateService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITranslateService/Initialize", ReplyAction="http://tempuri.org/ITranslateService/InitializeResponse")]
        System.Threading.Tasks.Task InitializeAsync(QuickyApp.TranslateApp.UI.TranslateService.DriverTypes driverType, string driverPath);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITranslateService/Translate", ReplyAction="http://tempuri.org/ITranslateService/TranslateResponse")]
        System.Threading.Tasks.Task<QuickyApp.TranslateApp.UI.TranslateService.TranslateWord> TranslateAsync(QuickyApp.TranslateApp.UI.TranslateService.TranslateWord word, QuickyApp.TranslateApp.UI.TranslateService.TranslateLanguages translatedLanguage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITranslateService/Detect", ReplyAction="http://tempuri.org/ITranslateService/DetectResponse")]
        System.Threading.Tasks.Task<QuickyApp.TranslateApp.UI.TranslateService.TranslateWord> DetectAsync(QuickyApp.TranslateApp.UI.TranslateService.TranslateWord word);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITranslateServiceChannel : QuickyApp.TranslateApp.UI.TranslateService.ITranslateService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TranslateServiceClient : System.ServiceModel.ClientBase<QuickyApp.TranslateApp.UI.TranslateService.ITranslateService>, QuickyApp.TranslateApp.UI.TranslateService.ITranslateService {
        
        public TranslateServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Threading.Tasks.Task InitializeAsync(QuickyApp.TranslateApp.UI.TranslateService.DriverTypes driverType, string driverPath) {
            return base.Channel.InitializeAsync(driverType, driverPath);
        }
        
        public System.Threading.Tasks.Task<QuickyApp.TranslateApp.UI.TranslateService.TranslateWord> TranslateAsync(QuickyApp.TranslateApp.UI.TranslateService.TranslateWord word, QuickyApp.TranslateApp.UI.TranslateService.TranslateLanguages translatedLanguage) {
            return base.Channel.TranslateAsync(word, translatedLanguage);
        }
        
        public System.Threading.Tasks.Task<QuickyApp.TranslateApp.UI.TranslateService.TranslateWord> DetectAsync(QuickyApp.TranslateApp.UI.TranslateService.TranslateWord word) {
            return base.Channel.DetectAsync(word);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
    }
}
